### ISSUE TITLE
[NumberGuesser] Минуты

### ISSUE THREAD

**Issue by pavel-b-novikov** [filippova94/nsudotnet#1]
...считаются, увы, неправильно. Этот подход не прокатит, если мне хочется играть даже больше минуты (не говорю уже про час). Найдите другой способ.

**Comment by filippova94** [comment]
Исправила

**Comment by filippova94** [comment]
Исправила.

2016-05-04 13:24 GMT+06:00 Pavel Novikov <notifications@github.com>:
