### ISSUE TITLE
[LinesCounter] .Sum

### ISSUE THREAD

**Issue by pavel-b-novikov** [filippova94/nsudotnet#4]
`dirs.Sum(directory => LinesInDirectory(directory));`

А что будет если множество dirs пустое?

**Comment by filippova94** [comment]
Вернет 0

**Comment by pavel-b-novikov** [comment]
Ну а теперь откройте студию и проверьте

2016-05-23 1:04 GMT+06:00 Ekaterina Filippova notifications@github.com:

> Вернет 0
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/filippova94/nsudotnet/issues/4#issuecomment-220849796

## 

Sincerely yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by filippova94** [comment]
Именно эта функция возвращает 0.
if (dirs.Length.Equals(0))
                    Console.WriteLine(dirs.Sum(directory => LinesInDirectory(directory)));

**Comment by filippova94** [comment]
Или я неправильно понимаю вопрос.

**Comment by pavel-b-novikov** [comment]
Оу, пардон, my fault.
В общем диспозиция такова - enumerable-коллекциях эта радость действительно
работает нормально и вменяемо. Однако, когда дело доходит до баз данных, то
Sum при пустом множестве выдает довольно неприятный exception. В данном
случае идеологически правильный вариант записи -
.Select(c=>LinesCount(c)).DefaultIfEmpty(0).Sum();

2016-05-23 1:38 GMT+06:00 Ekaterina Filippova notifications@github.com:

> Или я неправильно понимаю вопрос.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/filippova94/nsudotnet/issues/4#issuecomment-220851590

## 

Sincerely yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by pavel-b-novikov** [comment]
Просто намотайте на ус
