### ISSUE TITLE
[Enigma] Строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [filippova94/nsudotnet#5]
По задаче в целом все нормально, однко строки.
У вас столько строк и они все такие красивые, что прямо-таки и просятся в ресурсы. Перетащите их туда и исправьте в коде.

**Comment by filippova94** [comment]
Исправила

**Comment by filippova94** [comment]
Не забудьте, пожалуйста, проверить эту задачу

**Comment by pavel-b-novikov** [comment]
Отлично. Возникло желание заставить вас делать локализацию, но черт с ним.
